import { z } from "zod"

/** Identifier of a persisted entity (generated by the database layer). */
export const idSchema = z.string().trim().min(1).max(64)

/** Calendar date without time, `YYYY-MM-DD` (e.g. a plan's start date). */
export const isoDateSchema = z.iso.date()
export type IsoDate = z.infer<typeof isoDateSchema>

/** Local time of day, 24-hour `HH:mm` (e.g. a reminder time). */
export const timeOfDaySchema = z
  .string()
  .regex(/^([01]\d|2[0-3]):[0-5]\d$/, { error: "Expected a time formatted as HH:mm" })
export type TimeOfDay = z.infer<typeof timeOfDaySchema>

export const locales = ["fr", "en"] as const
export const defaultLocale = "fr" satisfies Locale
export const localeSchema = z.enum(locales)
export type Locale = z.infer<typeof localeSchema>

/** Whether `value` is a time zone the runtime knows (IANA name such as `Europe/Paris`). */
export function isValidTimeZone(value: string): boolean {
  try {
    new Intl.DateTimeFormat("en-US", { timeZone: value })
    return true
  } catch {
    return false
  }
}

export const timeZoneSchema = z
  .string()
  .min(1)
  .refine(isValidTimeZone, { error: "Unknown IANA time zone" })

/** Day of the week, 0 = Sunday … 6 = Saturday (same convention as `Date#getDay`). */
export const weekdaySchema = z.int().min(0).max(6)
export type Weekday = z.infer<typeof weekdaySchema>

/** Non-empty set of weekdays, without duplicates. */
export const weekdaysSchema = z
  .array(weekdaySchema)
  .min(1)
  .refine((days) => new Set(days).size === days.length, { error: "Duplicate weekdays" })

export const allWeekdays: readonly Weekday[] = [0, 1, 2, 3, 4, 5, 6]
